apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    backend: mysql
  ports:
    - protocol: TCP
      port: 3306  # Port exposed by the service
      targetPort: 3306  # Port on which the MySQL Pod listens
