apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  # namespace: database
  labels:
    backend: mysql-deploy 
    env: staging              # Label for the Deployment
spec:
  replicas: 1                 # Number of desired replicas
  selector:
    matchLabels:
      app: mysql              # Selector to match pods managed by this Deployment
  template:
    metadata:
      labels:
        app: mysql           # Label for the pods created by this template
    spec:
      containers:
      - name: mysql          # Container name
        image: 883752638158.dkr.ecr.us-east-1.amazonaws.com/sql-image:mysql-latest  # Docker image to use
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"         # Environment variable for MySQL root password
        ports:
        - containerPort: 3306 # Port to expose
