apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-replicaset
  namespace: db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 883752638158.dkr.ecr.us-east-1.amazonaws.com/sql-image:mysql-latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306