apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: web
spec:
  # The number of replicas to be created
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    # Metadata for the Pods
    metadata:
      labels:
        app: employees
    # Pod specification
    spec:
      containers:
      - name: web-app
        image: 883752638158.dkr.ecr.us-east-1.amazonaws.com/webapp-image:webapp-latest
        # The Exposed port for the webapp
        ports:
        - containerPort: 8080
        # Environment variables
        env:
        - name: DBHOST
          value: "172.17.0.2"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD  
          value: "pw"
        - name: APP_COLOR
          value: "green"
